name: flutter_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  clay_containers: ^0.3.2
  eva_icons_flutter: ^3.0.0
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^9.0.0
  flutter_linkify: ^5.0.2
  url_launcher: ^6.0.4
  social_share: ^2.1.1
  rflutter_alert: ^2.0.2
  image_picker: ^0.7.5+3
  cloud_firestore: ^2.2.0
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  google_sign_in: ^5.0.4
  fluttertoast: ^8.0.7
  firebase_storage: ^8.1.3
  share_plus: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: BalsamiqSans
      fonts:
        - asset: fonts/BalsamiqSans-Regular.ttf
        - asset: fonts/BalsamiqSans-Regular.ttf

    - family: MeriendaOne
      fonts:
        - asset: fonts/MeriendaOne-Regular.ttf

    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Light.ttf
        - asset: fonts/Gilroy-Medium.ttf